name: Docker Build and Push

on:
  push:
    branches:
      - main  # 你可以根据需要修改为其他分支

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Ali Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com  # 替换为你的阿里云 Docker 镜像库地址
          username: ${{ secrets.ALI_HUB_USERNAME }}  # 使用 GitHub Secrets 存储阿里云用户名
          password: ${{ secrets.ALI_HUB_PASSWORD }}  # 使用 GitHub Secrets 存储阿里云密码

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./projects/app
          file: ./projects/app/Dockerfile  # 明确指定 Dockerfile 路径
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/ulquiola/fastgpt:latest  # 替换为你的镜像名称和标签
